### ISSUE TITLE
Doesn't reconnect 

### ISSUE THREAD

**Issue by ashnur** [liximomo/vscode-remote-fs#10]
If I leave the editor open and the other machines goes offline then comes back online, the plugin should probably reconnect but I don't see the **password** dialog. I have to close the workspace and open it again. And it doesn't keep the file contents, I have to duplicate all files and after reconnect and reopen manually copy the content back.

**Comment by liximomo** [comment]
I will remember your first password input and use it for auto reconnecting.

**Comment by ashnur** [comment]
1. I don't think it should remember the password for so much inactive time
2. I think what happens is that it tries to reconnect, it fails, and it doesn't try again, and there isn't a way to retrigger the connection to show the password again, because it already remembers it

**Comment by liximomo** [comment]
It will always try to reconnect if the connection is off. Maybe you can provide me the logs?

Just reproduce the problem and get the logs from View > Output > remotefs.

**Comment by prabal-banerjee** [comment]
Facing similar problem after local machine goes to sleep. No password dialog after waking up and the workspace freezes. 
Last line in the output : `[trace] stat /.vscode/extensions.json`
This file is actually not present on remote machine. Nor did I create it at any point.

**Comment by gelatosamantha** [comment]
I have the same problem too. However, I'm using the key file for authentication  I use remote FS to connect to my ec2 on AWS. Every time the SSH disconnected, it doesn't reconnect. I have to close the VS code and restart again to connect back to the server.

**Comment by liximomo** [comment]
Please try v0.0.12.

**Comment by gelatosamantha** [comment]
wow, fantastic!!! 
It's working perfectly now.
Thanks so much~~
