### ISSUE TITLE
How do I refresh the view of a remote directory's contents?

### ISSUE THREAD

**Issue by fcahoon** [liximomo/vscode-remote-fs#14]
I created a new file on my remote system with 'cp' and when I went to edit my new file in VSCode, I couldn't get it to show up. I eventually quit and restarted VSCode which worked.

In other remote editing tools I've used (such as Remote System Explorer in Eclipse), you could right-click on a folder and choose "Refresh" from the context menu to pick up new files that were created remotely.

Can something like that be added to vscode-remote-fs? Or is it there and I'm not finding it?

**Comment by liximomo** [comment]
How do you refresh the view of a local directory?

**Comment by medifle** [comment]
@liximomo 
It makes sense to refresh the view of remote dir.
Why can't it sync bidirectionally?
