### ISSUE TITLE
Code Outline compatibility?

### ISSUE THREAD

**Issue by cdsaenz** [liximomo/vscode-remote-fs#17]
Hi, fabulous extension, made my switch to VSCode possible. Thanks a lot.
Now one of things I'd love to have is a simple Code Outline, I downloaded said extension (couldn't find another yet) and it works fine with local files but comes up with nothing for remotefs-opened files.. Do you know about that or have any workaround to try for Code Outline to work with remotefs? Thanks once more.

**Comment by liximomo** [comment]
This should be an issue of "Code Outline".
