### ISSUE TITLE
Please add upload file feature

### ISSUE THREAD

**Issue by JohnyByk** [liximomo/vscode-remote-fs#24]
Now, if you want to upload local file you must use external solution (for example: FileZilla, Total Commander). Possibility to upload local files will be great. Yo can aad refresh feature too. Right clik on folder -> Refresh files ;).

BTW. Awsome Plugin :)

**Comment by molokovskikh** [comment]
I join to issue, it will be fit.
Also feature would be great  if drag&drop files between remote and local places like a did in Idea (JetBrains)

**Comment by liximomo** [comment]
@JohnyByk You can just drag local files to explorer to upload files.

**Comment by molokovskikh** [comment]
> @JohnyByk You can just drag local files to explorer to upload files.

But not whole directory.
