### ISSUE TITLE
enhancement: Backup the files which are being edited in the remote

### ISSUE THREAD

**Issue by suryasr007** [liximomo/vscode-remote-fs#3]
The extension is pretty good. It would be grateful if the following feature is added:

Backing up the files which are edited in remote to our local system will help in the recovery as well comparison.

**Comment by liximomo** [comment]
For what you want. You may need [vscode-sftp](https://github.com/liximomo/vscode-sftp).

**Comment by suryasr007** [comment]
HI @liximomo, I think we cannot work directly on remote files using the [vscode-sftp](https://github.com/liximomo/vscode-sftp). It syncs remote -> local and vice versa. But what I have requested is similar to  [remote-ftp](https://atom.io/packages/remote-ftp)

**Comment by liximomo** [comment]
You can combine both `vscode-sftp` with `vscode-remote-fs`. It's more power than `remote-ftp`.
`vscode-sftp` foucs on editing local file and sync to remote. `vscode-remote-fs` foucs on editng remote files without **download** them first.

**Comment by suryasr007** [comment]
Thanks for the suggestion.
