### ISSUE TITLE
Cannot find module '../helpers/getRemoteIdentityFromUri'

### ISSUE THREAD

**Issue by fstanis** [liximomo/vscode-remote-fs#4]
Not sure if this is a known issue, but seems that there's a problem in the [version of Remote FS that's on the Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=liximomo.remotefs): VSCode fails to load it because it can't find the `../helpers/getRemoteIdentityFromUri` module.

Looking at the built files, it seems that, for some reason, the file is called "getRemoteIdentityFrom**URI**.js" instead of "getRemoteIdentityFrom**Uri**.js", so this is an issue in case-sensitive filesystems (e.g. on Linux). Doesn't seem to be the case with the source file in this repo, so I'm assuming it's fixed, but would be good to update the one in the Marketplace since it's broken right now.

**Comment by liximomo** [comment]
Thanks for your information.

Filip Stanis <notifications@github.com> 于 2018年5月15日周二 19:36写道：

**Comment by liximomo** [comment]
I've updated an new version. Please tell me if this still happens.

**Comment by fstanis** [comment]
That fixed it - thank you.
