### ISSUE TITLE
Javascript Intellisense not working when editing remote files

### ISSUE THREAD

**Issue by mosfetish** [liximomo/vscode-remote-fs#46]
Code's built-in Intellisense works perfectly for PHP and CSS when editing remote files but Javascript does not. Works fine on local files.

NOTE: when editing a remote HTML file, within script tags the javascript intellisense works perfectly. Just not with standalone javascript files.

Remote FS is a fantastic extension but this a very frustrating issue. I note an earlier issue that specifies the same problem with C/C++ files.

**Comment by liximomo** [comment]
There is nothing we can do here. We need other extensions to adapt the remote fs protocol.

**Comment by mosfetish** [comment]
> We need other extensions to adapt the remote fs protocol.

What does that mean? Is editing javascript files remotely forbidden by VS Code? Why does it make a difference if the file is remote since it's being edited in local memory?

**Comment by liximomo** [comment]
Because every file is a resource identified by URI like 'file:///paht/to/file'. And the remote files URI didn't have the `file:` scheme. Some extensions only work with files with a `file:` scheme.

**Comment by mosfetish** [comment]
> Because every file is a resource identified by URI like 'file:///paht/to/file' in vscode. And the remote files URI didn't have the `file:` scheme. Some extensions only work with files with a `file:` scheme.

Sure. So the problem is with Code, not Remote FS? Or can Remote FS be made to work with non-File scheme files?

**Comment by liximomo** [comment]
There nothing I can do. They must to adapt remote fs protocol.

**Comment by mosfetish** [comment]
> There nothing I can do. They must adapt vscode remote fs protocol.

I'm sorry but you're still not explaining the problem. They must adapt? Who is they? VS Code? Are you saying there's a problem with VS Code's own protocol that prevents intellisense working correctly on remote files? Are you saying VS Code prevents intellisense on remote javascript files? And only javascript files? because intellisense works fine on PHP, CSS and javascript WITHIN HTML script tags, but not in standalone javascript files.
