### ISSUE TITLE
Remote Folder name in Explorer: How to change?

### ISSUE THREAD

**Issue by tzcole** [liximomo/vscode-remote-fs#47]
Hi,

First off, Great extension.  Just moved over to VScode, and this plugin is a must for my workflow.

One thing I'm having trouble with is I have a workspace with multiple remote server folders.  The name for any remote folder as listed under Explorer uses `<username> (Remote)`.  Since my username is the same across servers, all my remote folders have the same name.  It would be nice if there were a <description> parameter in the remote server config which could uniquely identify the remote server.  Perhaps fail back to either the label defined in User Settings for the remote server or even the hostname parameter.

Cheers,
tzcole

**Comment by liximomo** [comment]
There is a parameter named `name`.

**Comment by tzcole** [comment]
I tried adding a name parameter, but it's not taking.  Tried unloading/re-loading extension, closing/opening vscode, removing and re-adding the remote folder.  It's still showing the remote folders display as `<username> (Remote)`.  

BTW, I'm using Remote FS 0.0.12.

Here is my User Settings block.

`    "remotefs.remote": {
      "stats": {
        "scheme": "sftp",
        "host": "my.hostname.com",
        "username": "myuserid",
        "privateKeyPath": "/Users/xxx/.ssh/id_rsa",
        "name": "myname",
        "rootPath": "/opt/home/myuserid"
      },
`


Cheers,
tzcole

**Comment by liximomo** [comment]
There is a new setting `remotefs.rootLabel` in v0.0.13

**Comment by tzcole** [comment]
That works great now.  Thank you very much.

Cheers,
tzcole

**Comment by liximomo** [comment]
Thanks for the support.

**Comment by Naramsim** [comment]
Just for clarity: you can set the name dynamically with this `rootLabel`

```
"remotefs.rootLabel": "${name} — (Remote)",
```

**Comment by igorcafe** [comment]
I tried adding this to my VSCode `settings.json`:
```json
"remotefs.remote": {
	"10.0.1.116": {
		"name": "1.116",
		"scheme": "sftp",
		"host": "10.0.1.116",
		"username": "root",
		"rootPath": "/usr/local/telco-data/slaview/customfilesOp/scripts"
	},
	"10.0.1.117": {
		"name": "1.117",
		"scheme": "sftp",
		"host": "10.0.1.117",
		"username": "root",
		"rootPath": "/usr/local/telco-data/slaview/customfilesOp/scripts"
	},
},
"remotefs.rootLabel": "${name} — (Remote)",
```

But it still shows this after reloading:
![image](https://user-images.githubusercontent.com/85039990/137522558-82c3646f-2fcf-49a9-886a-3e90a9eb3f04.png)

**Comment by Naramsim** [comment]
This extension is bit outdated, I moved to SSH FS

**Comment by ErtyHackward** [comment]
SSH FS does not work with ftp. 



> I tried adding this to my VSCode `settings.json`:
> 
> ```json
> "remotefs.remote": {
> 	"10.0.1.116": {
> 		"name": "1.116",
> 		"scheme": "sftp",
> 		"host": "10.0.1.116",
> 		"username": "root",
> 		"rootPath": "/usr/local/telco-data/slaview/customfilesOp/scripts"
> 	},
> 	"10.0.1.117": {
> 		"name": "1.117",
> 		"scheme": "sftp",
> 		"host": "10.0.1.117",
> 		"username": "root",
> 		"rootPath": "/usr/local/telco-data/slaview/customfilesOp/scripts"
> 	},
> },
> "remotefs.rootLabel": "${name} — (Remote)",
> ```
> 
> But it still shows this after reloading: ![image](https://user-images.githubusercontent.com/85039990/137522558-82c3646f-2fcf-49a9-886a-3e90a9eb3f04.png)

You need to remove existing folders from workspace and re-add them (ctrl+shift+p)
