### ISSUE TITLE
[Feature Request] Please add .ignore function

### ISSUE THREAD

**Issue by whmrtm** [liximomo/vscode-remote-fs#48]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Win, Linux]
 - VSCode Version [e.g. 1.27.0]
 - Extension Version [e.g. 1.7.0]

**Extension Logs** - *required*
You can get the logs from View > Output > remote-fs.

**Comment by liximomo** [comment]
Use "files.exclude" setting.

**Comment by diego898** [comment]
@liximomo how would I use this to show/hide all of my `.` files? `.bashrc`, etc.?

**Comment by vintagesucks** [comment]
@diego898 

```
"files.exclude": {
  "**/.*": true
}
```

Note: `files.exclude` is a VS Code setting, not a `vscode-remote-fs` setting.
