### ISSUE TITLE
Using remotefs.rootLabel with each individual entry

### ISSUE THREAD

**Issue by jarnalyrkar** [liximomo/vscode-remote-fs#52]
As I understand it, I can use remotefs.rootLabel to set a label in the tree view that every remotefs instance uses. However, it is set for all instances, and so doesn't help to distinguish one remote from another. Would it be possible to set this attribute for each instance, so it's easy to distinguish one from another?

**Comment by liximomo** [comment]
Use `${name}` variable.

**Comment by joel6653** [comment]
I'm having trouble getting this to work. Could you give an example of a snippet from a configuration file with two remotes and separate root labels for each? Here is what I've tried:

{
   
    "remotefs.remote": {

        


        "Wyoming": {
 
            // string - sftp or ftp
            "scheme": "sftp", 
           
            // string - Hostname or IP address of the server.
            "host": "ftp.wyomingmi.gov",
          
            // integer - Port number of the server.
            "port": 22,
          
            // string - Username for authentication.
            "username": "hidden",
          
             // string - Password for password-based user authentication.
            "password": "hidden",
          
            // string - An absolute path on remote. This will be the root path of remote file system.
            "rootPath": "/", 
          
            // integer - How long (in milliseconds) to wait for the connect to complete. 
            "connectTimeout": 10000,
        },
        "realjoel": {
 
            // string - sftp or ftp
            "scheme": "sftp", 
           
            // string - Hostname or IP address of the server.
            "host": "ftp.realjoel.com",
          
            // integer - Port number of the server.
            "port": 22,
          
            // string - Username for authentication.
            "username": "hidden",
          
             // string - Password for password-based user authentication.
            "password": "hidden",
          
            // string - An absolute path on remote. This will be the root path of remote file system.
            "rootPath": "/home/realjoel/public_html", 
          
            // integer - How long (in milliseconds) to wait for the connect to complete. 
            "connectTimeout": 10000,
        }

    },
    
    "remotefs.rootLabel": "Wyoming — Wyoming",
    "remotefs.rootlabel": "realjoel - realjoel"
}

both connections want to use the first label ("Wyoming")
