### ISSUE TITLE
Typo in the repo headline

### ISSUE THREAD

**Issue by xShirase** [liximomo/vscode-remote-fs#53]
**Describe the bug**

The repo headline says "Working with any file in everywhere with **vscdoe**."

**To Reproduce**
1. Go to https://github.com/liximomo/vscode-remote-fs
2. Click on Nothing
3. See error

**Expected behavior**
It should say vsc**od**e

**Screenshots**

**Desktop (please complete the following information):**
web

**Extension Logs** - *required*

**Comment by liximomo** [comment]
Thanks.
