### ISSUE TITLE
FileSystemProvider (FTP) wrongly returns size as string and not number

### ISSUE THREAD

**Issue by bpasero** [liximomo/vscode-remote-fs#56]
Heads up, found this while looking into https://github.com/Microsoft/vscode/issues/72909. The FTP provider seems to return `FileStat` where size is of type `string` but not `number`. 

![image](https://user-images.githubusercontent.com/900690/56798894-0aba5c00-6818-11e9-8bec-233522a87649.png)

**Comment by gjsjohnmurray** [comment]
@liximomo I think the fix needs to go [here (code pointer)](https://github.com/liximomo/vscode-remote-fs/blob/88b67ff683a05998d79bd4fb8466f7ca518d0f51/src/fs-providers/FTPProvider.ts#L172)

Insert this clause (or similar):
```
    if (typeof target.size === 'string') {
      target.size = +target.size;
    }
```

**Comment by liximomo** [comment]
Nice catch.

**Comment by liximomo** [comment]
Fixed.
