### ISSUE TITLE
 No passphrase dialog is shown.

### ISSUE THREAD

**Issue by vega231** [liximomo/vscode-remote-fs#9]
Getting error "Encrypted private key detected, but no passphrase given"

...and no passphrase dialog is shown (don't want to save it in config for security reasons)

**Comment by TMorville** [comment]
I am getting the same error, but while using a ssh key?

``Encrypted private key detected, but no passphrase given``

```
Settings:

{

    "remotefs.remote": {
        "dev": {
          "privateKeyPath": "<path to key>",
          "scheme": "sftp",
          "host": "<host name>",
          "username": "<username>"",
          "rootPath": "<root path>""
        }
      }
    
}
```

**Comment by diego898** [comment]
@TMorville how did you solve your error?

**Comment by kreshnik01** [comment]
You don't need to hardcode the passphrase in sftp.json, just add `"passphrase": true` and a vscode popup will prompt when you hit save to enter your passphrase.
